// packages/demo-site/src/frameworks/react/examples/ShadcnControlled.tsx
import { useState } from "react";
import { tabs } from "slidytabs";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/shadcn/react/tabs";

export default () => {
  const [value, setValue] = useState("correct");

  return (
    <Tabs
      value={value}
      onValueChange={(newValue) => newValue !== "battery" && setValue(newValue)}
      ref={tabs()}
      className="text-center"
    >
      <TabsList className="[&>:nth-child(3)]:!text-red">
        <TabsTrigger value="correct">Correct</TabsTrigger>
        <TabsTrigger value="horse">Horse</TabsTrigger>
        <TabsTrigger value="battery">Battery</TabsTrigger>
        <TabsTrigger value="staple">Staple</TabsTrigger>
      </TabsList>
      <TabsContent value="correct">Correct</TabsContent>
      <TabsContent value="horse">Horse</TabsContent>
      <TabsContent value="battery">Battery</TabsContent>
      <TabsContent value="staple">Staple</TabsContent>
    </Tabs>
  );
};

// packages/demo-site/src/frameworks/svelte/examples/ShadcnControlled.svelte
<script lang="ts">
  import { tabs } from "slidytabs";
  import { Tabs, List, Trigger, Content } from "@/shadcn/svelte/tabs";
  let value = $state("correct");
</script>

<Tabs
  {@attach tabs()}
  bind:value={() => value, (next) => next !== "battery" && (value = next)}
>
  <List class="[&>:nth-child(3)]:!text-red">
    <Trigger value="correct">Correct</Trigger>
    <Trigger value="horse">Horse</Trigger>
    <Trigger value="battery">Battery</Trigger>
    <Trigger value="staple">Staple</Trigger>
  </List>
  <Content class="text-center" value="correct">Correct</Content>
  <Content class="text-center" value="horse">Horse</Content>
  <Content class="text-center" value="battery">Battery</Content>
  <Content class="text-center" value="staple">Staple</Content>
</Tabs>
