// packages/astro/src/components/tsx/examples/BasicExample.tsx
import { Tabs, TabsList, TabsTrigger } from "../tabs.js";
// import { rangetabs } from "slidytabs";

export default function () {
  return (
    <Tabs defaultValue="account" ref={() => {}}>
      <TabsList>
        <TabsTrigger value="account">Account</TabsTrigger>
        <TabsTrigger value="password">Password</TabsTrigger>
      </TabsList>
    </Tabs>
  );
}

// packages/astro/src/components/svelte/examples/basicExample.svelte
<script lang="ts">
  import * as Tabs from "../tabs";
  // import { rangetabs } from "slidytabs";
</script>

<Tabs.Root value="account" {@attach () => {}}>
  <Tabs.List>
    <Tabs.Trigger value="account">Account</Tabs.Trigger>
    <Tabs.Trigger value="password">Password</Tabs.Trigger>
  </Tabs.List>
</Tabs.Root>
