// packages/demo-site/src/frameworks/react/examples/Push.tsx
import { useState } from "react";
import { range, type RangeValue } from "slidytabs";
import { Tabs, TabsList, TabsTrigger } from "@/shadcn/tabs";

export default () => {
  const [value, onValueChange] = useState<RangeValue>([4, 6]);
  return (
    <Tabs ref={range({ value, onValueChange, push: true })}>
      <TabsList>
        {Array.from({ length: 11 }, (_, i) => (
          <TabsTrigger key={i} value={String(i)} className="min-w-0">
            {i}
          </TabsTrigger>
        ))}
      </TabsList>
    </Tabs>
  );
};

// packages/demo-site/src/frameworks/vue/examples/Push.vue
<script setup lang="ts">
import { ref } from "vue";
import { range, type RangeValue } from "slidytabs";
import { Tabs, TabsList, TabsTrigger } from "@/shadcn-vue/tabs";

const value = ref<RangeValue>([4, 6]);
const onValueChange = (newValue: RangeValue) => (value.value = newValue);
</script>

<template>
  <Tabs :ref="range({ value, onValueChange, push: true })" default-value="5">
    <TabsList>
      <TabsTrigger class="min-w-0" v-for="i in 11" :value="i - 1">{{
        i - 1
      }}</TabsTrigger>
    </TabsList>
  </Tabs>
</template>
