// packages/demo-site/src/frameworks/svelte/examples/Slider.svelte
<script lang="ts">
  import { slider } from "slidytabs";
  import * as Tabs from "@/shadcn-svelte/tabs";
  import { sharps, flats } from "@/lib/scales";
  const triggerClasses =
    "min-w-0 ring-inset rounded-lg h-full !shadow-none data-[state=active]:(bg-zinc-300 rounded-none) data-[state=inactive]:text-zinc-500";

  let value = $state(0);
  const onValueChange = (newValue: number) => (value = newValue);
</script>

<div class="flex flex-col gap-4">
  {#each [flats, sharps] as scale}
    <Tabs.Root value={scale[value]} {@attach slider({ value, onValueChange })}>
      <Tabs.List class="p-0 overflow-hidden w-88">
        {#each scale as note}
          <Tabs.Trigger class={triggerClasses} value={note}>{note}</Tabs.Trigger
          >
        {/each}
      </Tabs.List>
    </Tabs.Root>
  {/each}
</div>

// packages/demo-site/src/frameworks/vue/examples/Slider.vue
<script setup lang="ts">
import { ref } from "vue";
import { slider } from "slidytabs";
import { Tabs, TabsList, TabsTrigger } from "@/shadcn-vue/tabs";
import { sharps, flats } from "@/lib/scales";
const triggerClasses =
  "min-w-0 ring-inset rounded-lg h-full !shadow-none data-[state=active]:(bg-zinc-300 rounded-none) data-[state=inactive]:text-zinc-500";

const value = ref(0);
const onValueChange = (newValue: number) => (value.value = Number(newValue));
</script>

<template>
  <div class="flex flex-col gap-4">
    <Tabs
      :ref="slider({ value, onValueChange })"
      :default-value="scale[value]"
      v-for="scale in [flats, sharps]"
    >
      <TabsList class="p-0 overflow-hidden w-88">
        <TabsTrigger
          :class="triggerClasses"
          v-for="note in scale"
          :value="note"
          >{{ note }}</TabsTrigger
        >
      </TabsList>
    </Tabs>
  </div>
</template>
