// packages/demo-site/src/frameworks/svelte/examples/Vertical.svelte
<script lang="ts">
  import { slider } from "slidytabs";
  import * as Tabs from "@/shadcn-svelte/tabs";
</script>

<Tabs.Root {@attach slider()} value="account" orientation="vertical">
  <Tabs.List class="h-full flex-col items-stretch">
    <Tabs.Trigger value="account">Account</Tabs.Trigger>
    <Tabs.Trigger value="password">Password</Tabs.Trigger>
  </Tabs.List>
</Tabs.Root>

// packages/demo-site/src/frameworks/vue/examples/Vertical.vue
<script setup lang="ts">
import { slider } from "slidytabs";
import { Tabs, TabsList, TabsTrigger } from "@/shadcn/vue/tabs";
</script>

<template>
  <Tabs :ref="slider()" default-value="account" orientation="vertical">
    <TabsList class="h-full flex-col items-stretch">
      <TabsTrigger value="account">Account</TabsTrigger>
      <TabsTrigger value="password">Password</TabsTrigger>
    </TabsList>
  </Tabs>
</template>
