// packages/demo-site/src/frameworks/react/examples/Vertical.tsx
import { slider } from "slidytabs";
import { Tabs, TabsList, TabsTrigger } from "@/shadcn/tabs";

export default () => (
  <Tabs ref={slider()} defaultValue="account" orientation="vertical">
    <TabsList className="h-full flex-col items-stretch">
      <TabsTrigger value="account">Account</TabsTrigger>
      <TabsTrigger value="password">Password</TabsTrigger>
    </TabsList>
  </Tabs>
);

// packages/demo-site/src/frameworks/vue/examples/Vertical.vue
<script setup lang="ts">
import { slider } from "slidytabs";
import { Tabs, TabsList, TabsTrigger } from "@/shadcn/vue/tabs";
</script>

<template>
  <Tabs :ref="slider()" default-value="account" orientation="vertical">
    <TabsList class="h-full flex-col items-stretch">
      <TabsTrigger value="account">Account</TabsTrigger>
      <TabsTrigger value="password">Password</TabsTrigger>
    </TabsList>
  </Tabs>
</template>
