// packages/demo-site/src/frameworks/svelte/examples/Tabs.svelte
<script lang="ts">
  import * as Tabs from "@/shadcn/svelte/tabs";
  import { tabs } from "slidytabs";
</script>

<Tabs.Root {@attach tabs()} value="account" class="text-center">
  <Tabs.List>
    <Tabs.Trigger value="account">Account</Tabs.Trigger>
    <Tabs.Trigger value="password">Password</Tabs.Trigger>
  </Tabs.List>
  <Tabs.Content value="account">Account</Tabs.Content>
  <Tabs.Content value="password">Password</Tabs.Content>
</Tabs.Root>

// packages/astro/src/components/vue/examples/Tabs.vue
<script setup lang="ts">
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@shadcn-vue/tabs";
import { tabs } from "slidytabs";
</script>

<template>
  <Tabs :ref="tabs()" default-value="account" class="text-center">
    <TabsList>
      <TabsTrigger value="account">Account</TabsTrigger>
      <TabsTrigger value="password">Password</TabsTrigger>
    </TabsList>
    <TabsContent value="account">Account</TabsContent>
    <TabsContent value="password">Password</TabsContent>
  </Tabs>
</template>
