// packages/astro/src/components/tsx/examples/Tabs.tsx
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@shadcn-react/tabs";
import { tabs } from "slidytabs";

export default () => (
  <Tabs defaultValue="password" ref={tabs()} className="text-center">
    <TabsList>
      <TabsTrigger value="account">Account</TabsTrigger>
      <TabsTrigger value="password">Password</TabsTrigger>
    </TabsList>
    <TabsContent value="account">Account</TabsContent>
    <TabsContent value="password">Password</TabsContent>
  </Tabs>
);

// packages/astro/src/components/vue/examples/Tabs.vue
<script setup lang="ts">
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@shadcn-vue/tabs";
import { tabs } from "slidytabs";
</script>

<template>
  <Tabs :ref="tabs()" default-value="account" class="text-center">
    <TabsList>
      <TabsTrigger value="account">Account</TabsTrigger>
      <TabsTrigger value="password">Password</TabsTrigger>
    </TabsList>
    <TabsContent value="account">Account</TabsContent>
    <TabsContent value="password">Password</TabsContent>
  </Tabs>
</template>
