// packages/demo-site/src/frameworks/svelte/examples/Range.svelte
<script lang="ts">
  import { range, type RangeValue } from "slidytabs";
  import * as Tabs from "@/shadcn/svelte/tabs";

  let value: RangeValue = $state([4, 6]);
  const onValueChange = (next: RangeValue) => (value = next);
</script>

<Tabs.Root {@attach range({ value, onValueChange })}>
  <Tabs.List>
    {#each { length: 11 }, i}
      <Tabs.Trigger class="min-w-0" value={i.toString()}>{i}</Tabs.Trigger>
    {/each}
  </Tabs.List>
</Tabs.Root>

// packages/demo-site/src/frameworks/react/examples/Range.tsx
import { useState } from "react";
import { type RangeValue, range } from "slidytabs";
import { Tabs, TabsList, TabsTrigger } from "@/shadcn/tabs";

export default () => {
  const [value, onValueChange] = useState<RangeValue>([4, 6]);
  return (
    <Tabs ref={range({ value, onValueChange })}>
      <TabsList>
        {Array.from({ length: 11 }, (_, i) => i.toString()).map((i) => (
          <TabsTrigger key={i} value={i} className="min-w-0">
            {i}
          </TabsTrigger>
        ))}
      </TabsList>
    </Tabs>
  );
};
