// packages/demo-site/src/frameworks/svelte/examples/Sticky.svelte
<script lang="ts">
  import { slider, type SliderOptions } from "slidytabs";
  import * as Tabs from "@/shadcn-svelte/tabs";

  let sticky = $state(5);
  const onValueChange = (next: number) => (sticky = next);
</script>

{#snippet Slider(sliderOptions: SliderOptions)}
  <Tabs.Root value={sticky.toString()} {@attach slider(sliderOptions)}>
    <Tabs.List>
      {#each { length: 11 }, i}
        <Tabs.Trigger class="min-w-0" value={i.toString()}>{i}</Tabs.Trigger>
      {/each}
    </Tabs.List>
  </Tabs.Root>
{/snippet}

<div class="even:*:col-span-2 grid grid-cols-3 gap-x-8 gap-y-4 items-center">
  <div>Choose sticky:</div>
  {@render Slider({ value: sticky, onValueChange })}
  <div>Sticky applied:</div>
  {@render Slider({ sticky })}
</div>

// packages/demo-site/src/frameworks/react/examples/Sticky.tsx
import { useState } from "react";
import { slider, type SliderOptions } from "slidytabs";
import { Tabs, TabsList, TabsTrigger } from "@/shadcn/react/tabs";
const triggerClasses =
  "min-w-0 ring-inset rounded-lg h-full !shadow-none data-[state=active]:(bg-gray-300 rounded-none) data-[state=inactive]:text-neutral-500";

const Slider = (sliderOptions: SliderOptions) => (
  <Tabs defaultValue={"5"} ref={slider(sliderOptions)}>
    <TabsList className="p-0 overflow-hidden">
      {Array.from({ length: 11 }, (_, i) => (
        <TabsTrigger key={i} value={i.toString()} className={triggerClasses}>
          {i}
        </TabsTrigger>
      ))}
    </TabsList>
  </Tabs>
);

export default () => {
  const [sticky, setSticky] = useState(5);

  return (
    <div className="even:children:col-span-2 grid grid-cols-3 gap-x-8 gap-y-4 items-center">
      <div>Choose sticky:</div>
      <Slider value={sticky} onValueChange={setSticky} />
      <div>Sticky applied:</div>
      <Slider sticky={sticky} />
    </div>
  );
};
