// packages/astro/src/components/svelte/examples/NumbersRange.svelte
<script lang="ts">
  import * as Tabs from "$lib/shadcn/tabs";
  import { rangetabs, type RangeValue } from "slidytabs";

  let value: RangeValue = $state([2, 4]);
  const onValueChange = (newValue: RangeValue) => (value = newValue);
</script>

<Tabs.Root {@attach rangetabs({ value, onValueChange })}>
  <Tabs.List>
    {#each { length: 11 }, i}
      <Tabs.Trigger value={String(i)} class="min-w-0">{i}</Tabs.Trigger>
    {/each}
  </Tabs.List>
</Tabs.Root>

// packages/astro/src/components/tsx/examples/NumbersRange.tsx
import { useState } from "react";
import { rangetabs, type RangeValue } from "slidytabs";
import { Tabs, TabsList, TabsTrigger } from "@/shadcn/tabs";

export default () => {
  const [value, onValueChange] = useState<RangeValue>([4, 6]);
  return (
    <Tabs ref={rangetabs({ value, onValueChange })}>
      <TabsList>
        {Array.from({ length: 12 }, (_, i) => (
          <TabsTrigger key={i} value={String(i)} className="min-w-0 px-2">
            {i}
          </TabsTrigger>
        ))}
      </TabsList>
    </Tabs>
  );
};
