// packages/astro/src/components/svelte/demo.svelte
<script lang="ts">
  import { codeToHtml } from "shiki";
  import BasicExample from "./basicExample.svelte";
  import exampleCode from "./basicExample.svelte?raw";

  const highlight = "{@attach () => {}}";
  const start = exampleCode.indexOf(highlight);
  const end = start + highlight.length;
  const properties = { class: "highlighted" };
  const decoration = { start, end, properties };
</script>

<div class="flex flex-col items-center p-4">
  Svelte / shadcn-svelte

  <BasicExample />
  {#await codeToHtml( exampleCode, { lang: "svelte", theme: "github-dark", decorations: [decoration] } ) then value}
    <div class="text-sm *:rounded-lg *:px-6 *:py-5">{@html value}</div>
  {/await}
</div>

// packages/astro/src/components/react/demo.tsx
import { BasicExample } from "./basicExample";
import exampleCode from "./basicExample?raw";
import ShikiHighlighter from "react-shiki";

const highlight = "ref={() => {}}";
const start = exampleCode.indexOf(highlight);
const end = start + highlight.length;
const properties = { class: "bg-neutral-600 rounded-sm p-1 -m-1" };

const decoration = { start, end, properties };

export default () => {
  return (
    <div className="flex items-center flex-col p-4">
      React / shadcn
      <BasicExample />
      <ShikiHighlighter
        className="text-sm"
        language="jsx"
        theme="github-dark"
        decorations={[decoration]}
      >
        {exampleCode}
      </ShikiHighlighter>
    </div>
  );
};
